USE [master]
GO
/****** Object:  Database [PERSONA]    Script Date: 17/6/2020 20:39:42 ******/
CREATE DATABASE [PERSONA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PERSONA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PERSONA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PERSONA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PERSONA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [PERSONA] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PERSONA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PERSONA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PERSONA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PERSONA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PERSONA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PERSONA] SET ARITHABORT OFF 
GO
ALTER DATABASE [PERSONA] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PERSONA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PERSONA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PERSONA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PERSONA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PERSONA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PERSONA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PERSONA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PERSONA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PERSONA] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PERSONA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PERSONA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PERSONA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PERSONA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PERSONA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PERSONA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PERSONA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PERSONA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PERSONA] SET  MULTI_USER 
GO
ALTER DATABASE [PERSONA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PERSONA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PERSONA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PERSONA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PERSONA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PERSONA] SET QUERY_STORE = OFF
GO
USE [PERSONA]
GO
/****** Object:  Table [dbo].[PERSONA]    Script Date: 17/6/2020 20:39:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PERSONA](
	[id_persona] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[apellido] [varchar](50) NOT NULL,
	[fechaNac] [date] NOT NULL,
	[documento] [varchar](10) NOT NULL,
 CONSTRAINT [PK_PERSONA] PRIMARY KEY CLUSTERED 
(
	[id_persona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [PERSONA] SET  READ_WRITE 
GO
